package com.neveralone.models;
// Generated Dec 9, 2015 8:37:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int id;
     private String email;
     private String password;
     private Date dob;
     private char gender;
     private char interestedIn;
     private boolean status;
     private Date createdAt;

    public Users() {
    }

    public Users(int id, String email, String password, Date dob, char gender, char interestedIn, boolean status, Date createdAt) {
       this.id = id;
       this.email = email;
       this.password = password;
       this.dob = dob;
       this.gender = gender;
       this.interestedIn = interestedIn;
       this.status = status;
       this.createdAt = createdAt;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public char getGender() {
        return this.gender;
    }
    
    public void setGender(char gender) {
        this.gender = gender;
    }
    public char getInterestedIn() {
        return this.interestedIn;
    }
    
    public void setInterestedIn(char interestedIn) {
        this.interestedIn = interestedIn;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


